-- =============================================================================
-- UPDATE FIELD VISITS TABLE TO NEW FORMAT
-- =============================================================================

-- 1. Identity and ID Fix (to prevent unique constraint errors)
ALTER TABLE field_visits ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('field_visits', 'id'), (SELECT MAX(id) FROM field_visits));

-- 2. Rename existing columns to match new format where possible
ALTER TABLE field_visits RENAME COLUMN organization_name TO field_visited;
ALTER TABLE field_visits RENAME COLUMN programme TO program_name;
ALTER TABLE field_visits RENAME COLUMN location TO city;
ALTER TABLE field_visits RENAME COLUMN faculty_coordinator TO staff_name;

-- 2. Add new columns for counts with exact names
ALTER TABLE field_visits ADD COLUMN IF NOT EXISTS visited_date VARCHAR(20);
ALTER TABLE field_visits ADD COLUMN IF NOT EXISTS no_of_student_visited INTEGER DEFAULT 0;
ALTER TABLE field_visits ADD COLUMN IF NOT EXISTS no_of_staff_visited INTEGER DEFAULT 0;

-- 3. Remove student-specific columns (No longer one-per-student)
ALTER TABLE field_visits DROP COLUMN IF EXISTS enrollment_number;
ALTER TABLE field_visits DROP COLUMN IF EXISTS student_name;
ALTER TABLE field_visits DROP COLUMN IF EXISTS visit_date;
ALTER TABLE field_visits DROP COLUMN IF EXISTS department;

-- 4. Ensure visit_date is available (it should already be there)
-- No change needed for visit_date.

-- 5. Update RLS policies (just in case)
DROP POLICY IF EXISTS "Allow all for anon - field_visits" ON field_visits;
CREATE POLICY "Allow all for anon - field_visits" ON field_visits FOR ALL USING (true) WITH CHECK (true);
